# Generated by Django 5.1.7 on 2026-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tashkilot nomi', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Tashkilot logotipi', null=True, upload_to='organization/logos/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('payment_soon', 'To‘lov yaqin'), ('not_paid', 'To‘lov qilmagan')], default='active', help_text='Tashkilot holati', max_length=20)),
                ('phone', models.CharField(help_text='Telefon raqam (login sifatida ishlatiladi)', max_length=20, unique=True)),
                ('password', models.CharField(help_text='Parol (hashlangan holda saqlanadi)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
