# Generated by Django 5.1.7 on 2026-02-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('OFITSIANT', 'Ofitsiant'), ('OSHPAAZ', 'Oshpaz'), ('KASSIR', 'Kassir'), ('MENEJER', 'Menejer'), ('ADMIN', 'Administrator')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branch.branch')),
            ],
        ),
    ]
