# Generated by Django 5.1.7 on 2026-02-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_created_at_alter_branch_is_active_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(help_text='Xodim ishlaydigan filial.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yozuv yaratilgan vaqt (avtomatik).'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Xodim faol yoki yo‘qligi.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Xodimning to‘liq ismi.', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='Telefon raqami (unikal bo‘lishi kerak).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('OFITSIANT', 'Ofitsiant'), ('OSHPAZ', 'Oshpaz'), ('KASSIR', 'Kassir'), ('MENEJER', 'Menejer'), ('ADMIN', 'Administrator')], help_text='Xodim lavozimi.', max_length=20),
        ),
    ]
