# Generated by Django 5.1.7 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_branch_alter_employee_created_at_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Xodim ishlaydigan tashkilot.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti (avtomatik).'),
        ),
    ]
