# Generated by Django 5.1.7 on 2026-03-11 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_organization_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='face_password',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Face password 4 xonali bo‘lishi kerak')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Parol 4 xonali bo‘lishi kerak')]),
        ),
    ]
