# Generated by Django 5.1.7 on 2026-02-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('kitchen', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='order.order'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='ready_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_tickets', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tickets', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='kitchenticketitem',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_ticket_items', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='kitchenticketitem',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenticket'),
        ),
    ]
