# Generated by Django 5.1.7 on 2026-02-18 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_created_at_alter_branch_is_active_and_more'),
        ('employee', '0002_alter_employee_branch_alter_employee_created_at_and_more'),
        ('kitchen', '0002_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenticket',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Qabul qilingan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='accepted_by',
            field=models.ForeignKey(help_text='Ticketni qabul qilgan oshpaz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tickets', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='branch',
            field=models.ForeignKey(help_text='Ticket qaysi filialga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Ticket yaratilgan vaqt (avtomatik).'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='kind',
            field=models.CharField(choices=[('INITIAL', 'Asosiy yuborish'), ('ADDITION', 'Qo‘shimcha yuborish')], help_text='Yuborish turi (asosiy yoki qo‘shimcha).', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='order',
            field=models.ForeignKey(help_text='Bog‘langan buyurtma.', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='order.order'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='ready_at',
            field=models.DateTimeField(blank=True, help_text='Tayyor bo‘lgan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='ready_by',
            field=models.ForeignKey(help_text='Taomni tayyor deb belgilagan xodim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_tickets', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='sent_by',
            field=models.ForeignKey(help_text='Ticketni yuborgan xodim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tickets', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('COOKING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('CANCELLED', 'Bekor qilindi')], default='NEW', help_text='Oshxona jarayon holati.', max_length=20),
        ),
        migrations.AlterField(
            model_name='kitchenticket',
            name='table_number_snapshot',
            field=models.CharField(help_text='Buyurtma yuborilgan paytdagi stol raqami (snapshot).', max_length=50),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt (avtomatik).'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='name_snapshot',
            field=models.CharField(help_text='Taom nomi (yuborilgan paytdagi holati).', max_length=255),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='note_snapshot',
            field=models.TextField(blank=True, help_text='Qo‘shimcha izoh (snapshot).', null=True),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='order_item',
            field=models.ForeignKey(help_text='Asl buyurtma elementi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_ticket_items', to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Miqdori.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='kitchenticketitem',
            name='ticket',
            field=models.ForeignKey(help_text='Qaysi kitchen ticketga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenticket'),
        ),
    ]
