# Generated by Django 5.1.7 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_kitchenticket_accepted_at_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenticket',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='ready_at',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='ready_by',
        ),
        migrations.RemoveField(
            model_name='kitchenticket',
            name='table_number_snapshot',
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Ticket qaysi tashkilotga tegishli.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='kitchenticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Ticket oxirgi yangilangan vaqt (avtomatik).'),
        ),
        migrations.DeleteModel(
            name='KitchenTicketItem',
        ),
    ]
