# Generated by Django 5.1.7 on 2026-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Filial yozuvi yaratilgan sana va vaqt. Bu maydon avtomatik ravishda to‘ldiriladi va o‘zgartirilmaydi.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Filial faol yoki faol emasligini bildiradi. Agar False bo‘lsa, filial tizimda o‘chirilgan emas, lekin vaqtincha ishlamaydi.'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text="Filialning to‘liq nomi. Masalan: 'Chilonzor filiali' yoki 'Main Office'. Bu nom tizim bo‘ylab filialni aniqlash uchun ishlatiladi.", max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='Asia/Tashkent', help_text="Filial joylashgan hududning vaqt mintaqasi (timezone). Masalan: 'Asia/Tashkent'. Bu vaqt bilan bog‘liq hisob-kitoblar va loglar uchun ishlatiladi.", max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Filial ma’lumotlari oxirgi marta qachon yangilanganini ko‘rsatadi. Har safar saqlanganda avtomatik yangilanadi.'),
        ),
    ]
