# Generated by Django 5.1.7 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_created_at_alter_branch_is_active_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='timezone',
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Ushbu filial qaysi tashkilotga tegishli ekanligini ko‘rsatadi.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.organization'),
        ),
    ]
