# Generated by Django 5.1.7 on 2026-02-14 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('kitchen_name_snapshot', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('COOKING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('CANCELLED', 'Bekor qilindi')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('dine_in', 'Dine in (zalda)'), ('takeaway', 'Takeaway (olib ketish)'), ('delivery', 'Delivery (yetkazib berish)')], max_length=20)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent_to_kitchen', 'Oshxonaga yuborildi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('served', 'Berildi'), ('payment_pending', 'To‘lov kutilmoqda'), ('paid', 'To‘lov olindi'), ('closed', 'Yopildi'), ('cancelled', 'Bekor qilindi')], default='draft', max_length=30)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_kitchen_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='branch.branch')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
