# Generated by Django 5.1.7 on 2026-02-18 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_created_at_alter_branch_is_active_and_more'),
        ('employee', '0002_alter_employee_branch_alter_employee_created_at_and_more'),
        ('order', '0002_initial'),
        ('table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='assigned_waiter',
            field=models.ForeignKey(help_text='Mas’ul ofitsiant.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(help_text='Buyurtma qaysi filialga tegishli.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Yopilgan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='UZS', help_text='Valyuta kodi (masalan: UZS).', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chegirma summasi.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, help_text='Mehmonlar soni.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Buyurtmaning yagona UUID identifikatori.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Bloklangan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='Buyurtmani vaqtincha bloklagan foydalanuvchi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Buyurtmaga umumiy izoh.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='Buyurtma raqami (unikal).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='opened_by',
            field=models.ForeignKey(help_text='Buyurtmani ochgan foydalanuvchi.', on_delete=django.db.models.deletion.PROTECT, related_name='opened_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, help_text='Tayyor bo‘lgan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sent_to_kitchen_at',
            field=models.DateTimeField(blank=True, help_text='Oshxonaga yuborilgan vaqt.', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Servis haqi.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_kitchen', 'Oshxonaga yuborildi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('served', 'Berildi'), ('payment_pending', 'To‘lov kutilmoqda'), ('paid', 'To‘lov olindi'), ('closed', 'Yopildi'), ('cancelled', 'Bekor qilindi')], default='draft', help_text='Buyurtma joriy holati.', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Chegirmasiz jami summa.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, help_text='Stol (agar dine-in bo‘lsa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='table.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soliq summasi.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Yakuniy to‘lanadigan summa.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('dine_in', 'Dine in (zalda)'), ('takeaway', 'Takeaway (olib ketish)'), ('delivery', 'Delivery (yetkazib berish)')], help_text='Buyurtma turi (zal, takeaway, delivery).', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqti.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Kim kiritdi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='kitchen_name_snapshot',
            field=models.CharField(help_text='Oshxona nomi snapshot.', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, help_text='Umumiy summa (unit_price x qty).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, help_text='Qo‘shimcha izoh.', null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Qaysi buyurtmaga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Mahsulot (o‘chirilgan bo‘lsa NULL).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='table.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(help_text='Mahsulot nomi snapshot.', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, help_text='Soni/miqdori.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi'), ('COOKING', 'Tayyorlanmoqda'), ('READY', 'Tayyor'), ('CANCELLED', 'Bekor qilindi')], default='NEW', help_text='Hozirgi holati.', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Bir dona narxi.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='actor',
            field=models.ForeignKey(help_text='O‘zgartirgan xodim.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Vaqea log vaqti.'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='event',
            field=models.CharField(help_text='Vaqea nomi.', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='from_status',
            field=models.CharField(blank=True, help_text='Avvalgi holat.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Qo‘shimcha ma’lumot (JSON).'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='order',
            field=models.ForeignKey(help_text='Qaysi buyurtma.', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='to_status',
            field=models.CharField(blank=True, help_text='Yangi holat.', max_length=30, null=True),
        ),
    ]
