# Generated by Django 5.1.7 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_options_alter_order_assigned_waiter_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='opened_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='kitchen_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name_snapshot',
        ),
        migrations.AddField(
            model_name='order',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Buyurtma qaysi tashkilotga tegishli.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Buyurtma elementi qaysi tashkilotga tegishli.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='OrderStatusLog',
        ),
    ]
