# Generated by Django 5.1.7 on 2026-03-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_currency_remove_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal_amount',
        ),
    ]
