# Generated by Django 5.1.7 on 2026-03-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_subtotal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='Buyurtma raqami (unikal).', max_length=20),
        ),
    ]
