# Generated by Django 5.1.7 on 2026-03-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sent_to_kitchen_at',
        ),
    ]
