# Generated by Django 5.1.7 on 2026-02-18 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_created_at_alter_branch_is_active_and_more'),
        ('order', '0003_alter_orderitem_options_alter_order_assigned_waiter_and_more'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Yaratilgan vaqt.'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Yaratilgan vaqt.'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Oxirgi yangilanish vaqti.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(help_text='Kategoriya qaysi filialga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Kategoriya nomi.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(help_text='Mahsulot qaysi filialga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Mahsulot kategoriyasi.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='table.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mahsulot sotuvda faol yoki yo‘qligi.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kitchen_name',
            field=models.CharField(help_text='Oshxonada ishlatiladigan nom.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Mahsulot nomi.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Mahsulot narxi.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='table',
            name='active_order',
            field=models.ForeignKey(blank=True, help_text='Hozir biriktirilgan faol buyurtma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tables', to='order.order'),
        ),
        migrations.AlterField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(help_text='Stol qaysi filialga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Yaratilgan vaqt.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Stol faol yoki yo‘qligi.'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, help_text='Stol nomi yoki qo‘shimcha belgi (ixtiyoriy).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(help_text='Stol raqami (filial ichida unikal).'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('FREE', 'Bo‘sh'), ('BUSY', 'Band'), ('PAYMENT', 'Hisob jarayonida'), ('CLOSED', 'Yopilgan')], default='FREE', help_text='Stolning joriy holati.', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['branch', 'name'], name='table_categ_branch__738d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['branch', 'category'], name='table_produ_branch__e26dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'number'], name='table_table_branch__dd8f0d_idx'),
        ),
    ]
