# Generated by Django 5.1.7 on 2026-02-27 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_remove_branch_timezone_branch_organization'),
        ('organization', '0001_initial'),
        ('table', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='table',
            name='table_table_branch__dd8f0d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('branch', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Kategoriya qaysi tashkilotga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Mahsulot qaysi tashkilotga tegishli.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Stol qaysi tashkilotga tegishli.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='organization.organization'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'name'], name='table_table_branch__7cfdc2_idx'),
        ),
        migrations.RemoveField(
            model_name='table',
            name='active_order',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
